id: opecha:P004316
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG5724
  title: བོད་ཞི་བས་བཅིངས་འགྲོལ་བཏང་ནས་ལོ་ངོ་ལྔ་བཅུ་འཁོར་བར་དྲན་གསོ་ཞུ་བའི་རྩོམ་ཡིག་ཕྱོགས་བསྒྲིགས་
  volume: ''
  author: ''
